#!/bin/sh
TRAEFIK_VERSION=$1
DOCKER_REPO=${DOCKER_REPO:-jochen}

if [ "${TRAEFIK_VERSION}" = "" ]; then
    echo "Usage: $0 <traefik version>"
    exit 1
fi

if ! docker buildx inspect traefik; then
    docker buildx create \
        --name traefik \
        --driver docker-container \
        --platform linux/arm64,linux/amd64 \
        --bootstrap \
        --use
fi

docker buildx build \
    --builder traefik-builder \
    --platform linux/arm64,linux/amd64 \
    --build-arg TRAEFIK_VERSION=${TRAEFIK_VERSION} \
    --tag ${DOCKER_REPO}/traefik:v${TRAEFIK_VERSION} \
    --push .